### ISSUE TITLE
Broken facial_recog_tests???

### ISSUE THREAD

**Issue by gould-ann** [samaritan-security/samaritan-backend#72]
For some reason, when I pull from master, most of the facial_recog_tests are broken.

Did someone fix this? Please don't push code if it breaks all of the tests

<img width="478" alt="Screen Shot 2020-03-27 at 1 10 08 PM" src="https://user-images.githubusercontent.com/7882770/77786732-4b27e880-702c-11ea-8d62-ea781ab550f6.png">

```
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Users/anngould/IdeaProjects/samaritan-backend/tests/facial_recog_tests.py", line 146, in test_compare_frame_and_encodings
    all_ids, all_encodings = get_all_people_information()
  File "/Users/anngould/IdeaProjects/samaritan-backend/FacialRecog.py", line 93, in get_all_people_information
    npy = np.fromiter(iterable, float)
ValueError: could not convert string to float: '[161,'
```

If this is broken, I can look into it... Just wondering if someone else had already fixed it though.

**Comment by gould-ann** [comment]
LMK if you guys have ran into this before or not ASAP.

**Comment by katebrune** [comment]
![image](https://user-images.githubusercontent.com/31379789/77787315-5a5b6600-702d-11ea-865a-1673752ebb06.png)

the only error i get is because the camera is off so it can't make the connection

**Comment by rgoluch** [comment]
It works fine for me as well with IntelliJ. The only failure is the camera connection because there isn't a camera connected. Please run from the command line instead of the button.
![Screen Shot 2020-03-27 at 1 20 05 PM](https://user-images.githubusercontent.com/25016831/77787604-c9d15580-702d-11ea-927e-cb22e1300efb.png)

**Comment by katebrune** [comment]
i think the problem is that your local db might still have old contents in it. run app.py then in postman run DELETE localhost:5000/test to clear the dbs, then run api_tests.py to fill it with data in the current format and run the tests again to see if it works and let me know.

**Comment by rgoluch** [comment]
You can't run the unit tests just by running it from the buttons in IntelliJ since it runs them with python instead of python3- thus they fail. 
![Screen Shot 2020-03-27 at 1 23 27 PM](https://user-images.githubusercontent.com/25016831/77787825-38aeae80-702e-11ea-9a7c-f35a9f9eca02.png)

**Comment by gould-ann** [comment]
> i think the problem is that your local db might still have old contents in it. run app.py then in postman run DELETE localhost:5000/test to clear the dbs, then run api_tests.py to fill it with data in the current format and run the tests again to see if it works and let me know.

this fixed it I'm going to see if I can add that in the setUp @katebrune

**Comment by gould-ann** [comment]
> You can't run the unit tests just by running it from the buttons in IntelliJ since it runs them with python instead of python3- thus they fail.
> ![Screen Shot 2020-03-27 at 1 23 27 PM](https://user-images.githubusercontent.com/25016831/77787825-38aeae80-702e-11ea-9a7c-f35a9f9eca02.png)

my device is set up to run python 3.7 when you run the `python` command. Button/command line doesn't make a difference, but I tried to see if it was that. @rgoluch
